c:\users\sid\desktop\gpgpu\bin\win64\debug\template.ilk
c:\users\sid\desktop\gpgpu\bin\win64\debug\template.exe
c:\users\sid\desktop\gpgpu\bin\win64\debug\template.pdb
c:\users\sid\desktop\gpgpu\bin\win64\debug\template.lib
c:\users\sid\desktop\gpgpu\bin\win64\debug\template.exp
c:\users\sid\desktop\gpgpu\hw0\template\x64\debug\main.cu.cache
c:\users\sid\desktop\gpgpu\hw0\template\x64\debug\main.cu.obj
c:\users\sid\desktop\gpgpu\hw0\template\../../bin/win64/debug/template.exe
c:\users\sid\desktop\gpgpu\hw0\template\x64\debug\template.tlog\link.command.1.tlog
c:\users\sid\desktop\gpgpu\hw0\template\x64\debug\template.tlog\link.read.1.tlog
c:\users\sid\desktop\gpgpu\hw0\template\x64\debug\template.tlog\link.write.1.tlog
c:\users\sid\desktop\gpgpu\hw0\template\x64\debug\template.tlog\template.write.1u.tlog
